version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis-srv
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander-web
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_EXPORTER_DEBUG=1
    ports:
      - 9121:9121
    depends_on:
      - redis

  prometheus-server:
    image: prom/prometheus
    ports:
        - 9090:9090
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - redis-exporter

  grafana-ui:
    image: grafana/grafana
    ports:
        - 3000:3000
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
        - prometheus-server:prometheus

  producer-java:
    container_name: vendas-producer-java
    hostname: vendas-producer-java
    image: vendas-producer-java:01
    restart: always
    depends_on:
      - redis
    ports:
      - "9091:9091"

  consumer-java-1:
    container_name: vendas-consumer-java-1
    hostname: vendas-consumer-java-1
    image: vendas-consumer-java:01
    restart: always
    depends_on:
      - redis
    ports:
      - "9092:9092"

  consumer-java-2:
    container_name: vendas-consumer-java-2
    hostname: vendas-consumer-java-2
    image: vendas-consumer-java:01
    restart: always
    depends_on:
      - redis
    ports:
      - "9093:9092"

  consumer-java-3:
    container_name: vendas-consumer-java-3
    hostname: vendas-consumer-java-3
    image: vendas-consumer-java:01
    restart: always
    depends_on:
      - redis
    ports:
      - "9094:9092"

  consumer-node-1:
    container_name: vendas-consumer-node-1
    hostname: vendas-consumer-node-1
    image: vendas-consumer-node:01
    restart: always
    depends_on:
      - redis

  consumer-node-2:
    container_name: vendas-consumer-node-2
    hostname: vendas-consumer-node-2
    image: vendas-consumer-node:01
    restart: always
    depends_on:
      - redis

  consumer-node-3:
    container_name: vendas-consumer-node-3
    hostname: vendas-consumer-node-3
    image: vendas-consumer-node:01
    restart: always
    depends_on:
      - redis
